/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110089-gbc589c91f7-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
